// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgGarnn3OPgaD6bG2teigEA9nGJvv3RA0',
    appId: '1:214167789:android:19e0791367993687245ce4',
    messagingSenderId: '214167789',
    projectId: 'my-firebase-1234',
    storageBucket: 'my-firebase-1234.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI9TwC0A2MYmWLixL6svRWDpJ-L0F-kC4',
    appId: '1:214167789:ios:66f409aa67144072245ce4',
    messagingSenderId: '214167789',
    projectId: 'my-firebase-1234',
    storageBucket: 'my-firebase-1234.firebasestorage.app',
    iosClientId: '214167789-8mcuca2f7fa9asgn7dm9eehskj5p2eep.apps.googleusercontent.com',
    iosBundleId: 'com.memo.app.memoApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv-7QT3SzMjAJhOZFwa1If3Zs48mA8s5Y',
    appId: '1:214167789:web:a439761e1d005573245ce4',
    messagingSenderId: '214167789',
    projectId: 'my-firebase-1234',
    authDomain: 'my-firebase-1234.firebaseapp.com',
    storageBucket: 'my-firebase-1234.firebasestorage.app',
  );
}
